### ISSUE TITLE
Missing file (gitignore) when install

### ISSUE THREAD

**Issue by mrmlnc** [wejs/generator-wejs#4]
**Specs:**
 * Windows 10 (10130)
 * Node 12.4
 * NPM 2.10.1

**Sequence of actions:**
```
$ npm i -g yo we generator-wejs
$ cd test-wejs
$ yo wejs:app
```

**Error:**
```
? Your project name: test-we
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, no such file or directory 'C:\Users\Jack\AppData\Roaming\npm\node_modules\generator-wejs\app\templates\.gitignore'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Function.module.exports.sync (C:\Users\Jack\AppData\Roaming\npm\node_modules\generator-wejs\node_modules\yeoman-generator\node_modules\read-chunk\index.js:34:14)
    at copy (C:\Users\Jack\AppData\Roaming\npm\node_modules\generator-wejs\node_modules\yeoman-generator\lib\actions\actions.js:38:27)
    at yeoman.generators.Base.extend.writing.projectfiles (C:\Users\Jack\AppData\Roaming\npm\node_modules\generator-wejs\app\index.js:50:12)
    at C:\Users\Jack\AppData\Roaming\npm\node_modules\generator-wejs\node_modules\yeoman-generator\lib\base.js:428:16
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by albertosouza** [comment]
@mrmlnc thanks, this bug is fixed in master branch. 

I will update the generator file templates now and then i'll publish in npm

**Comment by albertosouza** [comment]
Fixed and templates updated

@mrmlnc check the lastest version in npm (v0.3.7)
